# -*- coding: utf-8 -*-
"""Task3&4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1N3C-GLJ9okmj40aH9ZjQMoUOl0XRObPa

task-3
go through other inbuilt methods like remove(),count(),clear(),sort(),reverse()
task-4
adding items and subtitles *italicized text*

Exercises on List
"""

x= [1,2,4,6,7]
rem=x.pop(3)
print(rem)
x

x.append("data science")
print(x)

type(x)

data= [2,3,4]
data[0]=1
data

list = [10, 20, [30, 40, [50, 60], 80], 90, 100]
list.insert(60,70)
list

list.insert(80,85)
list